In [1]:
import numpy as np

In [6]:
#Numpy 2_D Arrays
a = [0,1,2]
print(a[0])
print(a[-1])

b = [3,4,5]

c = [6,7,8]
z = [a,
     b,
     c]

0
2


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [7]:
a = np.arange(0,9)
z = a.reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#Slicing [rows:rows, columns:columns]
z[:2,0:2]

array([[0, 1],
       [3, 4]])

In [12]:
z[0:3:2, 0:3:2]

array([[0, 2],
       [6, 8]])