# Codio Coding Activity 2.2: Multidimensional NumPy Arrays

### Learning Outcome Addressed

- 2. Implement NumPy arrays, functions, and multidimensional arrays.


## Index:

- [Question 1](#Question-1)
- [Question 2](#Question-2)
- [Question 3](#Question-3)
- [Question 4](#Question-4)
- [Question 5](#Question-5)
- [Question 6](#Question-6)
- [Question 7](#Question-7)
- [Question 8](#Question-8)
- [Question 9](#Question-9)
- [Question 10](#Question-10)
- [Question 11](#Question-11)

### Multidimensional NumPy Arrays

*NumPy* multidimensional *arrays* are designed to store data in more than one dimension.


In general, *NumPy arrays* can have more than one dimension. One way to create such an *array* is to start with a one-dimensional *array* and use the *NumPy `reshape()`* *function* to rearrange elements of that *array* into a new shape.

The code:

```Python
a = np.array([1,2,3,4])
b = np.reshape(a, (2,2))

```

returns: *`b = ([[1, 2],[3, 4]])`*.

Note that the product of the dimension of the new *array* must be equal to the length of the original *array*.

Before beginning the activity, we need to import the library. Run the code cell below.


In [19]:
import numpy as np


### Question 1
*2 points*

In the code cell below, create a *NumPy array*, *`ans1a`*, with elements *`1,2,3,4,5` and `6`*.

Reshape *`ans1a`* into an *array* with two rows and three columns. Assign the result to *`ans1b`*.

In [20]:
### GRADED

### YOUR SOLUTION HERE
ans1a = np.array([1,2,3,4,5,6])
ans1b = np.reshape(ans1a,(2,3))

# YOUR CODE HERE

You can  define a *NumPy array* directly by using the *function `np.array()`*.


### Question 2
*2 points*

Define a *NumPy* *array*, *`ans2a`*, with elements in the first row equal to *`10,20,` and `30`* and  elements in the second row equal to *`5,10` and `15`*.

Reshape *`ans2a`* into a one-dimensional *array* with one row and six columns. Assign the result to *`ans2b`*.

In [21]:
### GRADED

### YOUR SOLUTION HERE
ans2a = np.array([[10,20,30],[5,10,15]])
ans2b = ans2a.reshape(1,6)

# YOUR CODE HERE
ans2b

array([[10, 20, 30,  5, 10, 15]])

### Indexing Arrays

Indexing *NumPy arrays* is very  similar to *indexing lists* and can be achieved by using the square brackets notation.

In a one-dimensional *array*, a single element can be accessed by specifying the *index* of the element within square brackets.

In [22]:
a = np.array([10,20,30,40])
a[0]

10

*Indexing* becomes a little more tricky when dealing with two-dimensional *arrays*. 

#### Accessing a Single Row or Column

A row in a 2-D *array* can be accessed by using a single *index* corresponding to the row you want to refer to.


### Question 3
*1 point*

The *array `my_array`* has been defined below.

Access the second row of *`my_array`* and assign it to *`ans3a`*.

In [23]:
my_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [24]:
### GRADED

### YOUR SOLUTION HERE
ans3a = my_array[1]

# YOUR CODE HERE
ans3a

array([4, 5, 6])

A column in a 2-D *array* can be accessed by using *slicing* notation.

For example,

```Python
x = np.array([[1,2,3],[4,5,6]])
y = x[:,1]
```
returns *`[2,5]`*. In the syntax above, the *`:`* symbol refers to all the rows of *`x,`* and the *index* *`1`* refers to the elements with *index* one in each row.

### Question 4
*2 points*

Consider the *array `my_array`* defined above. 

Access the last column of *`my_array`* and assign it to *`ans4a`*.

In [25]:
### GRADED

### YOUR SOLUTION HERE
ans4a = my_array[:, -1]

# YOUR CODE HERE
ans4a

array([3, 6, 9])

#### Accessing a Single Element

A single element in an *array* can be accessed by specifying the row and column *index* of the desired element within square brackets.

### Question 5
*1 point*

Consider the *array `my_array`* defined above. 

Access the element with value *`5`* and assign it to *`ans5a`*.

In [26]:
#my_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
### GRADED

### YOUR SOLUTION HERE
ans5a = my_array[1,1]

# YOUR CODE HERE
ans5a

5

### Slicing *Arrays*

Like to Python *lists*, *NumPy arrays* can be *sliced*. When *slicing* multidimensional *arrays*, you must specify a *slice* for each dimension of the *array*.

The *array `a`* is defined below with dimension 2 and shape `(3, 4)`.

In [27]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

### Question 6
*2 points*

Use *slicing* to pull out the *subarray* consisting of the first two rows and columns with indexes 1 and 2 of *`a`*. Assign the result to *`ans6a`*.

**HINT:** *`ans6a`* is the following *array* of shape (2, 2):
```Python
[[2 3]
[6 7]]
```

In [28]:
### GRADED

### YOUR SOLUTION HERE
ans6a = a[:2,1:3 ]

# YOUR CODE HERE
ans6a

array([[2, 3],
       [6, 7]])

A slice of an *array* is a view into the same data, so modifying it will modify the original *array*.

### Question 7
*1 point*

Consider again the *array `ans6a`* above.

What is the value of the element in *`ans6a[0][1]`*? Assign the result to *`ans7a`*.

In [29]:
### GRADED

### YOUR SOLUTION HERE
ans7a = 3

# YOUR CODE HERE
ans7a

3

### Broadcasting

Broadcasting is a powerful mechanism that allows *NumPy* to work with *arrays* of different shapes when performing arithmetic operations. 

Frequently, we have a smaller *array* and a larger *array*, and want to use the smaller *array* multiple times to perform some operation on the larger *array*.

Broadcasting typically makes your code faster and more concise, so you should strive to use it wherever possible.

### Question 8
*1 point*

Define an *array, `array_8a`* with dimension 2 and shape *`(4,3)`* and elements *`[0,0,0],[10,10,10],[20,20,20],[30,30,30]`*, and an *array, `array_8b` with elements `[0,1,0]`*.

Add *`array_8a`* and *`array_8b`* and assign the result to *`ans8a`*.

Print your result on the screen to visualize *`ans8a`*.

In [30]:
### GRADED

### YOUR SOLUTION HERE
array_8a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
array_8b = [0,1,0]
# YOUR CODE HERE
ans8a = array_8a+array_8b
ans8a

array([[ 0,  1,  0],
       [10, 11, 10],
       [20, 21, 20],
       [30, 31, 30]])

### Question 9
*3 points*

Define an *array, `array_9a,`* with dimension 2 and shape *`(3,4)`* and elements *`[0,0,0],[1,1,1],[2,2,2],[3,3,3]`*, and an *array, `array_9b`* with elements *`[1,1,-1]`*.

Add  *`array_9b`* to each row of *`array_9a`* and assign the result to *`ans9a`*.

**HINT:** For this question, start by creating an empty *array, `ans9a,`* with the same shape as *`array_9a`* by using the *function `empty_like(),`* and then use a *for* loop and *slicing* to add *`array_9b`* to *`array_9a`*.

In [31]:
### GRADED

### YOUR SOLUTION HERE
array_9a = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
array_9b = np.array([1,1,-1])
ans9a = np.empty_like(array_9a)
for i in range(4):
    ans9a[i,:]= array_9a[i, :] + array_9b

# YOUR CODE HERE


### More NumPy Functions

In the last section of this activity, you will practice some more advanced *NumPy functions*.

#### The Where Function

The *NumPy `where()` function* returns the *index* of the element in the *array* that satisfies a certain condition directly on the code.

For example:

```Python
a = np.array([2,4,5])
b = np.where(a>3)
```
returns *`[1,2]`*.


### Question 10
*2 points*

Define an *array, `array_10`* with dimension 2 and shape *`(3,3)`* and elements *`[0,0,0],[-1,1,-1],[2,-2,2]`*.

Extract the *indexes* of the elements of *`array_10`* that are greater than two. Assign the result to *`ans10a`*.

In [32]:
### GRADED

### YOUR SOLUTION HERE
array_10 = np.array([[0,0,0],[-1,1,-1],[2,-2,2]])
ans10a = np.where(array_10 > 2)

# YOUR CODE HERE
ans10a

(array([], dtype=int64), array([], dtype=int64))

#### The Extract Function

The *NumPy `extract()` function* returns the element that satisfies the condition, not the element *index*.

For example

```Python
a = np.array([2,4,5])
b = np.extract(a>3,a)
```
returns *`[4,5]`*.

### Question 11
*3 points*

Define an *array, `array_11,`* with dimension 2 and shape *`(3,3)`* and elements *`[0,0,0],[2,4,6],[3,6,9]`*.

Extract  the elements where the  modulo two division equals zero element from *`array_11`*. Assign the result to *`ans11a`*.
Delete the entries equal to zero in *`ans11a,`* and assign the result to *`ans11b`*.

In [33]:
### GRADED

### YOUR SOLUTION HERE
array_11 = np.array([[0,0,0],[2,4,6],[3,6,9]])
ans11a = np.extract(array_11 % 2 == 0, array_11)
ans11b = ans11a[ans11a != 0]

# YOUR CODE HERE